nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://192.168.1.51:30081'] # Your Angular URL
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*'] # Or restrict to your exact frontend URL
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
